method: Grad_Sim

task: "Counterfact"
subset: "Pythia-1b"

base_model_path: "EleutherAI/pythia-1b"
checkpoint: "DataAttributionEval/Pythia-1b-counterfactual"

device: "cuda"

save_path: ./results/factual-attribution-gradsim/
