method: Grad_Sim

task: "Toxicity/Bias"
subset: "XSTest-response-Het"

base_model_path: "EleutherAI/pythia-1b"
checkpoint: "DataAttributionEval/Pythia-1b-XSTest-response-Het"

device: "cuda"

save_path: ./results/toxicity-bias-gradsim/
